--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/xXWaterFrogzX/DeathSwap
build-by-default: true
branches:
- master
projects:
  PocketMine-MP.plugins.DeathSwap:
    path: PocketMine-MP/plugins/DeathSwap/
...
